# Start the Go app build
FROM golang:latest AS build

# Copy source
WORKDIR /app
COPY go.mod go.sum main.go ./

# Download dependencies
RUN go mod download

# Show the contents
RUN pwd && find ./

# Identify listening port
EXPOSE 8080

# Start the application
CMD ["go", "run", "main.go"]
